# Application Properties
server.port=8080
spring.main.allow-bean-definition-overriding=true
back.logPath = ../config/local-config.json


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

## Grafana
management.endpoints.web.exposure.include=health,info,metrics,prometheus


## jmDNS
spring.jmDNS.enabled=true
spring.jmDNS.service-type=_messenger._tcp.local.
spring.jmDNS.service-name=messenger-${HOSTNAME:unknown}
spring.jmDNS.service-port=${server.port}
spring.jmDNS.service-properties.description=Local Messenger Service
spring.jmDNS.service-properties.version=1.0.0


mdns.service.type=_messenger._tcp.local.
mdns.service.instance-name=messenger-${HOSTNAME:unknown}
mdns.service.announce-interval=10
mdns.discovery.scan-interval=15
mdns.auto-register=true

mdns.service.properties.description=Local Messenger Service
mdns.service.properties.version=1.0.0
mdns.service.properties.port=${server.port}


spring.application.name=MessengerService
spring.task.scheduling.enabled=true