# Springwolf AsyncAPI configuration
springwolf.docket.info.title=Local Messenger API
springwolf.docket.info.version=1.0.0
springwolf.docket.base-package=com.local_messenger.back
springwolf.docket.servers.local.protocol=ws
springwolf.docket.servers.local.host=localhost:8080
springwolf.docket.servers.local.pathname=/messenger

# Springwolf UI
springwolf.ui.enabled=true

# Springwolf Scanner
springwolf.scanner.stomp.listener.enabled=true
springwolf.scanner.stomp.payload.type=org.springframework.messaging.Message

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

## Grafana
management.endpoints.web.exposure.include=health,info,metrics,prometheus