# Application Properties
server.port=8080
spring.main.allow-bean-definition-overriding=true
back.logPath = ../config/local-config.json


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

## Grafana
management.endpoints.web.exposure.include=health,info,metrics,prometheus